---
title: "Census Data"
author: "Sterling Fearing"
date: "5/24/2021"
output: html_document
---

This code will generate a data frame with the demographic variables (population ages 15-49, race) and the economic variables (poverty, per capita income). 
Source: 2018 ACS US Census

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries

library(sf)
library(tidycensus)
library(tidyverse)
library(tigris)
library(tidyr)
library(here)

```

```{r}
# explore variables

# census_api_key("key", install = TRUE)

sVarNames <- load_variables(2018, "acs5/subject", cache = TRUE)
pVarNames <- load_variables(2018, "acs5/profile", cache = TRUE)
otherVarNames <- load_variables(2018, "acs5", cache = TRUE)

head(pVarNames)

## Demographic Variables

## identify variables from B01001 : AGE & SEX table
#  1. Female  : Age 15-17  B01001_030 Estimate!!Total!!Female!!15 to 17 years
#  2. Female  : Age 18-19  B01001_031 Estimate!!Total!!Female!!18 and 19 years
#  3. Female  : Age 20     B01001_032 Estimate!!Total!!Female!!20 years
#  4. Female  : Age 21     B01001_033 Estimate!!Total!!Female!!21 years
#  5. Female  : Age 22-24  B01001_034 Estimate!!Total!!Female!!22 to 24 years
#  6. Female  : Age 25-29  B01001_035 Estimate!!Total!!Female!!25 to 29 years
#  7. Female  : Age 30-34  B01001_036 Estimate!!Total!!Female!!30 to 34 years
#  8. Female  : Age 35-39  B01001_037 Estimate!!Total!!Female!!35 to 39 years
#  9. Female  : Age 40-44  B01001_038 Estimate!!Total!!Female!!40 to 44 years
# 10. Female  : Age 45-49  B01001_039 Estimate!!Total!!Female!!45 to 49 years


## identify variables from B02001: RACE table
#  1. Total Population  B02001_001 Estimate!!Total	
#  2. Race : White      B02001_002 Estimate!!Total!!White alone	
#  3. Race : Black      B02001_003 Estimate!!Total!!Black or African American alone	
#  4. Race : AmInd      B02001_004 Estimate!!Total!!American Indian and Alaska Native alone	
#  5. Race : Asian      B02001_005 Estimate!!Total!!Asian alone	
#  6. Race : PacificIs  B02001_006 Estimate!!Total!!Native Hawaiian and Other Pacific Islander alone	

## identify variables from B03002: HISPANIC OR LATINO ORIGIN BY RACE
#  1. Ethi : Hispanic   B03003_003 Estimate!!Total!!Hispanic or Latino	B03003_001 total pop


##Economic Variables

## identify variables from S1301: POVERTY STATUS IN THE PAST 12 MONTHS (Women aged 15-50)
#  S1301_C01_022: Estimate!!Total!!POVERTY STATUS IN THE PAST 12 MONTHS!!Women 15 to 50 years for whom poverty status is determined

# S1301_C01_023: Estimate!!Total!!POVERTY STATUS IN THE PAST 12 MONTHS!!Women 15 to 50 years for whom poverty status is determined!!Below 100 percent of poverty level

# S1301_C01_024: Estimate!!Total!!POVERTY STATUS IN THE PAST 12 MONTHS!!Women 15 to 50 years for whom poverty status is determined!!100 to 199 percent of poverty level

# S1301_C01_025: Estimate!!Total!!POVERTY STATUS IN THE PAST 12 MONTHS!!Women 15 to 50 years for whom poverty status is determined!!200 percent or more above poverty level



```


```{r}
# load variables

countyDf <- get_acs(geography = 'county', variables = c(age15_17 = "B01001_030",
                                                        age18_19 = "B01001_031",
                                                        age20 = "B01001_032",
                                                        age21 = "B01001_033",
                                                        age22_24 = "B01001_034",
                                                        age25_29 = "B01001_035",
                                                        age30_34 = "B01001_036",
                                                        age35_39 = "B01001_037",
                                                        age40_44 = "B01001_038",
                                                        age45_49 = "B01001_039",
                                                        popTot =  "B02001_001",
                                                        raceWhite = "B02001_002",
                                                        raceBlack = "B02001_003",
                                                        raceAmInd = "B02001_004",
                                                        raceAsian = "B02001_005",
                                                        racePacI = "B02001_006", 
                                                        raceHisp = "B03003_003",
                                                        pciE = "B19301_001",
                                                        povP = "S1701_C03_001"),
                    year = 2018, geometry = FALSE)

```

```{r}
# tidy data

# create one column for each variable, separate state and county
varDf <- countyDf %>%
  pivot_wider(names_from = variable, values_from = c(estimate, moe)) %>%
  separate(NAME, c("county", "state"), sep = ",") %>%
  separate(GEOID, into = c('stateFIPS', 'countyFIPS'), sep = 2, remove = FALSE)
  

# add pop for each age group to get pop est for age 15-49  
varDf$age15_49 <- varDf$estimate_age15_17 + varDf$estimate_age18_19 + varDf$estimate_age20 + varDf$estimate_age21 + varDf$estimate_age21 + varDf$estimate_age22_24 + varDf$estimate_age25_29 + varDf$estimate_age30_34 + varDf$estimate_age35_39 + varDf$estimate_age40_44 + varDf$estimate_age45_49
  
# calculate pop percent for each race
varDf$raceOther <-  varDf$estimate_popTot - (varDf$estimate_raceWhite + varDf$estimate_raceBlack + varDf$estimate_raceAmInd                       + varDf$estimate_raceAsian + varDf$estimate_racePacI)
varDf$whiteP  <-  round(varDf$estimate_raceWhite*100/varDf$estimate_popTot,2) 
varDf$blackP  <-  round(varDf$estimate_raceBlack*100/varDf$estimate_popTot,2)
varDf$amIndP  <-  round(varDf$estimate_raceAmInd*100/varDf$estimate_popTot,2)
varDf$asianP  <-  round(varDf$estimate_raceAsian*100/varDf$estimate_popTot,2)
varDf$pacIsP  <-  round(varDf$estimate_racePacI*100/varDf$estimate_popTot,2)
varDf$otherP  <-  round(varDf$raceOther*100/varDf$estimate_popTot,2)
varDf$hispP   <-  round(varDf$estimate_raceHisp*100/varDf$estimate_popTot,2)
  

# select variables of interest 
countyData <- varDf %>%
  select(GEOID, stateFIPS, countyFIPS, estimate_popTot, age15_49, whiteP, blackP, amIndP, asianP, pacIsP, hispP, otherP, estimate_povP, estimate_pciE) %>%
  rename(popTot = estimate_popTot,
         povPerc = estimate_povP,
         pciE = estimate_pciE) 

# remove PR, AK, HI
censusDataCounty <- countyData %>%
  filter(stateFIPS != "02" & stateFIPS != "72" & stateFIPS != "15")

# save as csv
write_csv(censusDataCounty,"data/censusDataCounty.csv")

```


