---
title: "Data Master"
output: html_document
date: '2022-07-19'
---
# Goal: Join data for analysis.

Spatial: Clinic location, geo boundaries (state, county)
Nearest Resource Analysis: Pre vs. Post Dobbs 
Demand: Age, Race, Income
Law: Pre vs. Post Dobbs
Political party: Legislative, governor, and state control 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries

library(tidyverse)
library(here)
library(dplyr)
library(sf)

```

```{r}
# load data

##County Variables: 

# Nearest Resource Analysis
NRAraw <- st_read(here("code/data/compareNRA.shp")) 

# Estimated demand
demandRaw <- read_csv(here("code/data/demand2.csv"))

# Census Data
censusRaw <- read_csv(here("code/data/censusDataCounty.csv"))

# Number of clinics

clinicCount <- read_csv(here("code/data/numClinics.csv"))


## State Variables: 

# Law Index (pre vs. post Dobbs)
lawRaw_pre <- read_csv(here("code/data/lawIndex.csv"))
lawRaw_post <- read_csv(here("code/data/lawI_PR.csv"))

# Political Party
partyRaw <- read_csv(here("code/data/stateParty.csv"))




```

```{r}
# reduce # of decimal places in dstChange column
# round to 10 decimal places 

NRAraw$dstChngS <- round(NRAraw$dstChng, digit= 5)
  
```

```{r}
# rename variables in clinic Count

clinicCount <- clinicCount %>%
  rename(countRoe = clinRoe,
         countDob = clinDob)

```


```{r}
# join county level variables 

# Rename NRA variables 

NRArename <- NRAraw %>%
  rename(stateFIPS = "sttFIPS",
         countyFIPS = "cntFIPS",
         distRoe = "minDst_R",
         distDobb = "mnDst_pR",
         distDif = "dstChng",
         distDifS = "dstChngS")

# join NRA to Estimated Demand

join_NRA_demand <- left_join(NRArename, demandRaw, by= "GEOID")

# join NRA/Estimated Demand to Census Data

join_census <- left_join(join_NRA_demand, censusRaw, by= "GEOID")

# join above to clinicCount

join_county <- left_join(join_census, clinicCount, by= "GEOID")

# remove duplicates

countyData <- join_county %>%
  select("GEOID", "stateFIPS.x", "countyFIPS.x", "county", "state", "popTot", "age15_49", "whiteP", "blackP", "amIndP", "asianP", "pacIsP", "hispP", "otherP", "povPerc", "pciE", "distRoe", "distDobb", "distDif", "distDifS", "ageD", "whiteD", "blackD", "asianD", "hispD", "raceD", "p100D", "p100_199D", "p200D", "incomeD", "totalD", "countRoe", "countDob", "geometry") %>%
  rename(stateFIPS = "stateFIPS.x",
         countyFIPS = "countyFIPS.x")

# create column for clinics per capita pop 

countyData <- countyData %>%
  mutate(clinRoe = (countRoe/age15_49)*100000)

countyData <- countyData %>%
  mutate(clinDob = (countDob/age15_49)*100000)


```

```{r}
# save shapefile for county data
st_write(countyData, here("code/data/countyMaster.shp"))

# save csv
write_csv(countyData, here("code/data/countyMaster.csv"))
```

```{r}
# join state level variables

# change variable name in Laws to match party (state_name = stateAB)
lawRaw_pre <- lawRaw_pre %>%
  rename(stateAB = state_name)

lawRaw_post <- lawRaw_post %>%
  rename(stateAB = state_name)

# join Political Party to Laws Under Roe
join_party_law <- left_join(partyRaw, lawRaw_pre, by= "stateAB")

# join Political Party/Laws Under Roe to Laws Under Dobbs
join_state <- left_join(join_party_law, lawRaw_post, by= "stateAB")

# rename variables
join_state_rename <- join_state %>%
  rename(gestRoe = gestational.x,
         fundRoe = funding.x,
         medRoe = medical.x,
         persRoe = personal.x,
         summRoe = overall.x,
         gestDobb = gestational.y,
         fundDobb = funding.y,
         medDobb = medical.y,
         persDobb = personal.y,
         summDobb = overall.y)

# add state geometry to save as shapefile
stateGeo <- st_read(here("code/data/stateLines.shp"))
# remove DC
state_removeDC <- stateGeo %>%
  filter(!str_detect(state, "District of Columbia"))
# join
stateMaster_geo <- full_join(join_state_rename, stateGeo, by = "stateFIPS")

```

```{r}
# save shapefile
st_write(stateMaster_geo, here("code/data/stateMaster.shp"))
# save as csv without geometry
write_csv(join_state_rename, here("code/data/stateMaster.csv"))
```

```{r}
# apply state variables across counties

join_state_county <- left_join(countyData, join_state_rename, by= "stateFIPS", keep= FALSE)

# remove repeating variables

dataComplete <- join_state_county %>%
  select(GEOID, stateFIPS, countyFIPS, county, state.x, popTot, age15_49, whiteP, blackP, amIndP, asianP, pacIsP, hispP, otherP, povPerc, pciE, countRoe, clinRoe, countDob, clinDob, distRoe, distDobb, distDif, distDifS, ageD, whiteD, blackD, asianD, hispD, raceD, p100D, p100_199D, p200D, incomeD, totalD, legCon, govCon, stateCon, gestRoe, fundRoe, medRoe, persRoe, summRoe, gestDobb, fundDobb, medDobb, persDobb, summDobb, geometry) %>%
  rename(state= "state.x")

```

```{r}
# save as shapefile

st_write(dataComplete, here("code/data/dataMaster.shp"))

# save as csv

write_csv(dataComplete, here("code/data/dataMaster.csv"))
```

