---
title: "Join Indices"
author: "Sterling Fearing"
date: "6/11/2022"
output: html_document
---

Goal: Join demand index, NRA, law index, and political rep. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries

library(tidyverse)
library(here)
library(dplyr)
library(sf)

```

```{r}
# load data

demandRaw <- read_csv(here("code/data/demandIndex.csv"))
NRAraw <- read_csv(here("code/data/NRA_noGeo.csv"))
lawRaw <- read_csv(here("code/data/lawIndexSum.csv"))
partyRaw <- read_csv(here("code/data/stateParty.csv"))
geo <- st_read(here("code/data/NRAcounty.shp"))
```

```{r}

# join tables for exploratory analysis

join1 <- left_join(demandRaw, NRAraw, by= "GEOID") %>%
  mutate(stateFIPS = stateFIPS.x) # change column name to match lawRaw

join2 <- left_join(join1, lawRaw, by= "stateFIPS")

join3 <- left_join(join2, partyRaw, by= "stateFIPS")
  
```

```{r}
# Select variables of interest for complete df and summary df

# create summary table with indices 
cleanSum <- join3 %>%
  select(GEOID, stateFIPS.x, countyFIPS.x, stateAB.x, county, minDist_mi, index, indexLAW, legCon, govCon, stateCon) # variable 'index'= indexD (demand summary)

# create table with all values 
cleanData <- join3 %>%
  select(GEOID, stateFIPS.x, countyFIPS.x, stateAB.x, county, age15_17D, age18_19D, age20_24D, age25_29D, age30_34D, age35_39D, age40_49D, age15_49D, whiteD, blackD, asianD, hispD, raceD, p100D, p100_199D, p200D, incomeD, age, race, income, index, minDist_mi, twoPhysV, gestLimV, pbBanV, pubFundAllV, privLimV, parentV, indexLAW, legCon, govCon, stateCon)
```

```{r}
# Rename variables 
# Suffixes:
# AB = abbreviation
# I = index
# D = demand
# V = value (post-scaling)


cleanSum2 <- cleanSum %>%
  rename(stateFIPS = stateFIPS.x,
         countyFIPS = countyFIPS.x,
         stateAB = stateAB.x,
         demandI = index,
         lawI = indexLAW,
         )

cleanData2 <- cleanData %>%
  rename(stateFIPS = stateFIPS.x,
         countyFIPS = countyFIPS.x,
         stateAB = stateAB.x, 
         ageD = age15_49D, 
         ageV = age, 
         raceV = race,
         incomeV = income,
         demandI = index, 
         lawI = indexLAW)

```

```{r}
# Add geometry

# select variables of interest from shp file 
selectgeo <- geo %>%
  select(GEOID, geometry)

# join complete table with geo
indexC <-left_join(cleanData2, selectgeo, by = "GEOID")

# join summary table with geo
indexS <- left_join(cleanSum2, selectgeo, by = "GEOID")


```

```{r}
# save csv files w/o geo

# index summaries
write_csv(cleanSum2, here("code/data/indexSummary.csv"))
# all variables
write_csv(cleanData2, here("code/data/indexAllVar.csv"))

# save summary table with geometry
write_sf(indexS, here("code/data/indexS.shp"), driver = "ESRI Shapefile")

# save complete table with geometry
write_sf(indexC, here("code/data/indexC.shp"), driver = "ESRI Shapefile")
```

