---
title: "Join Law Indices (Roe vs, Dobbs)"
output: html_document
date: '2022-07-19'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# libraries

library(purrr)
library(tidyverse)
library(here)
library(sf)
```

```{r}

# Join pre vs post Dobbs law

pre_Dobbs <- read_csv(here("code/data/lawIndexRoe.csv"))
post_Dobbs <- read_csv(here("code/data/lawI_PR.csv"))

```


```{r}
# join tables 

# remove repeating variables
# rename selected

post_Dobbs <- post_Dobbs %>%
  select(state_name, gestational, overall) %>%
  rename(gestDobb = gestational,
         lawDobb = overall)

join <- full_join(pre_Dobbs, post_Dobbs, by= "state_name")
  
join <- join %>%
  select(state_name, funding, medical, personal, gestational, overall, gestDobb, lawDobb) %>%
  rename(gestRoe = gestational, 
         lawRoe = overall)
```

```{r}
# save table for law index 

write_csv(join, here("code/data/RvD_law.csv"))
```

```{r}
# add state geometry 

stateLines <- st_read(here("code/data/stateLines.shp"))

# add party table (include state FIPS and state AB for join)

stateParty <- read_csv(here("code/data/stateParty.csv"))
```


```{r}
# join law and state party

renameState <- join %>%
  rename(stateAB = state_name)
  
lawParty <- full_join(renameState, stateParty, by= "stateAB" ) 

lawSelect <- lawParty %>%
  select(stateFIPS, stateAB, state, funding, medical, personal, gestRoe, gestDobb, lawRoe, lawDobb, legCon, govCon, stateCon)

# save csv with adjusted gest values and law summs

write_csv(lawSelect, here("code/data/compareLaw_adjGestVals.csv"))
```

```{r}
# join with geo

lawGeo <- left_join(lawSelect, stateLines, by= "stateFIPS")

# save as shapefile

st_write(lawGeo, here("code/data/comLaw_adjGestVals.shp"))

```

