---
title: "Law Index (Second Approach)"
author: "Sterling Fearing"
date: "6/10/2022"
output: html_document
---

Goal: Use strategy applied to demand index for consistent approach. (See treeindex.R from Dr. Kolak)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load libraries

library(tidyverse)
library(here)
```

```{r}
# load data
# source: lawIndex.Rmd, line 156, tempLawindex.csv

data <- read_csv(here("code/data/tempLawIndex2.csv"))
FIPS <- read_csv(here("code/data/stateLaw.csv"))

```

```{r}
# centers and/or scales the columns of a numeric matrix
# correct for directionality

data$twoPhysV <- -scale(data$twoPhysI)
data$gestLimV <- -scale(data$gestLimI)
data$pbBanV <- -scale(data$pbBanI)
data$pubFundAllV <- -scale(data$pubFundAllI)
data$privLimV <- -scale(data$privLimI)
data$parentV <- -scale(data$parentI)
data$twoTripsV <- -scale(data$twoTripsI)

```

```{r}
#Equally weight index 

data$indexLAW <-  ((data$twoPhysV + data$gestLimV + data$pbBanV + data$pubFundAllV + data$privLimV + data$parentV + data$twoTripsV)/7)
data$indexLAW <- as.numeric(data$indexLAW)

```

```{r}
# add state FIPS from stateLaw.csv

data <- data %>%
  mutate(stateAB = state) #change variable name to match

lawIndex <- full_join(FIPS, data, by = "stateAB") # join tables

# select variables of interest

lawIndex2 <- lawIndex %>%
  select(stateFIPS, stateAB, twoPhysV, gestLimV, pbBanV, pubFundAllV, privLimV, parentV, indexLAW)

# remove AK, HI 

lawIndex3 <- lawIndex2 %>%
  filter(stateFIPS != "02" & stateFIPS != "15")

```

```{r}
# save law index

write_csv(data, here("code/data/lawIndexFull.csv"))

write_csv(lawIndex3, here("code/data/lawIndexSum.csv"))
```

