---
title: "Urban/rural classification"
author: "Sterling Fearing"
date: "5/26/2021"
output: html_document
---
Goal: Load .csv files for urban/rural classifications for census tracts and counties from GeoDaCenter opiod-policy-scan. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr) # load csv from URL
library(here) # save files starting at wd
library(dplyr)
library(tidyverse)
```

```{r}
# census tracts 

urlfile = "https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/master/data_final/HS02_RUCA_T.csv"
URtract <- read_csv(url(urlfile))

write_csv(URtract, here("data/tractUrbanRural.csv"))

```

```{r}
# counties

urlfile = "https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/master/data_final/HS02_C.csv"
URcounty <- read_csv(url(urlfile))

write_csv(URcounty, here("data/countyUrbanRural.csv"))

```

```{r}
# Remove AK, HI, PR("NA") for abortion access analysis

## read in csv
URcounty <- read_csv("data/countyUrbanRural.csv")

## filter out AK and HI
df <- filter(URcounty, state != "AK")
df2 <- filter(df, state != "HI")

## save new csv

write_csv(df2, here("code/data/URcounty.csv"))


  

```

